server:
  port: 5002


datasource:
  sample-db:
    url: jdbc:mysql://localhost:3306/sample_db
    username: root
    password: my-dhr-pwd

liquibase:
  datasource:
    sample-db:
      url: jdbc:mysql://localhost:3306/sample_db
      username: root
      password: my-dhr-pwd
      changelog: classpath:migrations/local/db.changelog-local.xml