package com.example.api.vod.constant

enum class ErrorCode {

    METHOD_ARGUMENT_INVALID,
    PLAYLIST_SAVE_FAILED,
    PLAYLIST_NOT_FOUND,
    PLAYLIST_SEARCH_FAILED,
    PLAYLIST_DELETE_FAILED,
    PLAYLIST_ITEM_SAVE_FAILED,
    PLAYLIST_ITEM_NOT_FOUND
}